name: Destroy Cluster

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/checkout@v3
      
      ### Configure DO Credentials
      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{'${{'}} secrets.DO_TOKEN ${{'}}'}}
          
      - name: Restore Terraform state from cache
        uses: actions/cache@v2
        with:
          path: .terraform
          key: ${{'${{'}} runner.os ${{'}}'}}-terraform-${{'${{'}} hashFiles('**/*.tf') ${{'}}'}}
          restore-keys: |
            ${{'${{'}} runner.os ${{'}}'}}-terraform-

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform destroy
        run: terraform destroy -var "do_token=${{'${{'}} secrets.DO_TOKEN ${{'}}'}}" --auto-approve